server:
  port: 8081
  
file:
  report:
    directory: /reports

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092 # Use the Docker service name for Kafka
    streams:
      application-id: filewriter
      properties:
        auto.offset.reset: earliest
    topic:
      report-requests: report-requests