server:
  port: 8081
  
file:
  report:
    directory: D:\Chargepoint\reports/

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092 # Kafka broker address
    streams:
      application-id: file-writer-service # Mandatory for Kafka Streams
      properties:
        auto.offset.reset: earliest # Start reading from the beginning of the topic
    topic:
      report-requests: report-requests # Kafka topic name